# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Hugo Simple Theme"
license = "MIT"
licenselink = "https://github.com/StinkyPeach/hugo-simple-theme/blob/main/LICENSE"
description = "a simple, clean blog theme for hugo"
homepage = "https://github.com/StinkyPeach/hugo-simple-theme"
tags = ["blog", "light", "clean", "search"]
features = ["site search", "side bar"]
min_version = "0.41.0"

[author]
  name = "Devin"
  homepage = "https://github.com/StinkyPeach"

# If porting an existing theme
[original]
  name = "Huabing Zhao"
  homepage = "https://github.com/zhaohuabing/hugo-theme-cleanwhite"
  
